name: Conditional

on:
  workflow_dispatch:

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Main Branch Only
        if: github.ref == 'refs/head/main'
        run: echo "Running on main"
